### ISSUE TITLE
Problem generating French IPA

### ISSUE THREAD

**Issue by autumnkent** [martyngal/anki-ipa#21]
I can't seem to generate French IPA. I don't have any problem generating Russian or German. I'm seeing this problem on both Windows 10 and Linux Mint.
The debug info below is from my latest attempt. The only other add-ons installed were Review Heatmap and AwesomeTTS Google Cloud Text to Speech Unofficial.
Thanks for everything - this add-on is otherwise fantastic!

Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-08-23 15:40:21

--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1084, in emit
  File "C:\python38\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u025b' in position 37: character maps to <undefined>
Call stack:
  File "runanki", line 4, in <module>
  File "aqt\__init__.py", line 349, in run
  File "aqt\__init__.py", line 488, in _run
  File "aqt\webview.py", line 31, in cmd
  File "aqt\webview.py", line 97, in _onCmd
  File "aqt\webview.py", line 500, in _onBridgeCmd
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-2>", line 2, in onBridgeCmd
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 663, in repl
  File "C:\Users\Cate\AppData\Roaming\Anki2\addons21\799647424\main.py", line 183, in on_bridge_cmd
    _old(editor, command)
  File "aqt\editor.py", line 378, in onBridgeCmd
  File "C:\Users\Cate\AppData\Roaming\Anki2\addons21\799647424\main.py", line 68, in paste_ipa
    logging.debug(f"IPA transcription string: {ipa}")
  File "logging\__init__.py", line 2077, in debug
  File "logging\__init__.py", line 1422, in debug
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 950, in handle
  File "logging\__init__.py", line 1183, in emit
  File "logging\__init__.py", line 1089, in emit
Message: 'IPA transcription string: ɛtʁ'
Arguments: ()

**Comment by m-rtin** [comment]
Thanks for your feedback! Could you update to the newest version of the addon and try again? Could you send a screenshot? On my machine it looks like this:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/46455311/182034465-2ed8112b-b66a-48cb-8afb-af3f5951ee27.png">
